CREATE DATABASE CHL_ERASMOVE
USE CHL_ERASMOVE

CREATE TABLE ROLE (
    ROL_ID INT IDENTITY(1,1) NOT NULL,
    ROL_LABEL VARCHAR(50) NOT NULL,
    CONSTRAINT PK_ROLE PRIMARY KEY (ROL_ID)
)

CREATE TABLE ACCOUNT (
    ACC_ID INT IDENTITY(1,1) NOT NULL,
    ACC_EMAIL VARCHAR(150) NOT NULL,
    ACC_PASSWORD VARCHAR(255) NOT NULL,
    ACC_ROL_ID INT NOT NULL,
    CONSTRAINT PK_ACCOUNT PRIMARY KEY (ACC_ID),
    CONSTRAINT FK_ACCOUNT_ROLE FOREIGN KEY (ACC_ROL_ID) REFERENCES ROLE(ROL_ID)
)

CREATE TABLE TRAVELER (
    TRA_ID INT NOT NULL,
    TRA_FIRSTNAME VARCHAR(100) NOT NULL,
    TRA_LASTNAME VARCHAR(100) NOT NULL,
    TRA_PHONE VARCHAR(20) NULL,
    CONSTRAINT PK_TRAVELER PRIMARY KEY (TRA_ID),
    CONSTRAINT FK_TRAVELER_ACCOUNT FOREIGN KEY (TRA_ID) REFERENCES ACCOUNT(ACC_ID)
)

CREATE TABLE PLACE (
    PLA_ID INT IDENTITY(1,1) NOT NULL,
    PLA_NAME VARCHAR(150) NOT NULL,
    PLA_CITY VARCHAR(100) NOT NULL,
    PLA_COUNTRY VARCHAR(100) NOT NULL,
    PLA_LATITUDE DECIMAL(9,6) NULL,
    PLA_LONGITUDE DECIMAL(9,6) NULL,
    CONSTRAINT PK_PLACE PRIMARY KEY (PLA_ID)
)

CREATE TABLE TRANSPORT_TYPE (
    TTY_ID INT IDENTITY(1,1) NOT NULL,
    TTY_LABEL VARCHAR(50) NOT NULL,
    CONSTRAINT PK_TRANSPORT_TYPE PRIMARY KEY (TTY_ID)
)

CREATE TABLE TRANSPORT (
    TRP_ID INT IDENTITY(1,1) NOT NULL,
    TRP_TTY_ID INT NOT NULL,
    TRP_COMPANY VARCHAR(100) NOT NULL,
    TRP_REFERENCE VARCHAR(50) NULL,
    CONSTRAINT PK_TRANSPORT PRIMARY KEY (TRP_ID),
    CONSTRAINT FK_TRANSPORT_TRANSPORT_TYPE FOREIGN KEY (TRP_TTY_ID) REFERENCES TRANSPORT_TYPE(TTY_ID)
)

CREATE TABLE TRIP (
    TRI_ID INT IDENTITY(1,1) NOT NULL,
    TRI_DEPARTUREDATE DATETIME NOT NULL,
    TRI_ARRIVALDATE DATETIME NOT NULL,
    TRI_TRA_ID INT NOT NULL,
    TRI_PLA_ID INT NOT NULL,
    TRI_TRP_ID INT NOT NULL,
    CONSTRAINT PK_TRIP PRIMARY KEY (TRI_ID),
    CONSTRAINT FK_TRIP_TRAVELER FOREIGN KEY (TRI_TRA_ID) REFERENCES TRAVELER(TRA_ID),
    CONSTRAINT FK_TRIP_PLACE FOREIGN KEY (TRI_PLA_ID) REFERENCES PLACE(PLA_ID),
    CONSTRAINT FK_TRIP_TRANSPORT FOREIGN KEY (TRI_TRP_ID) REFERENCES TRANSPORT(TRP_ID)
)

INSERT INTO ROLE (ROL_LABEL) VALUES ('VOYAGEUR')
INSERT INTO ROLE (ROL_LABEL) VALUES ('GESTIONNAIRE')

INSERT INTO TRANSPORT_TYPE (TTY_LABEL) VALUES ('FLIGHT')
INSERT INTO TRANSPORT_TYPE (TTY_LABEL) VALUES ('TRAIN')
INSERT INTO TRANSPORT_TYPE (TTY_LABEL) VALUES ('BUS')

INSERT INTO ACCOUNT (ACC_EMAIL, ACC_PASSWORD, ACC_ROL_ID)
VALUES ('admin@erasmove.com', 'SuperMotDePasse!123', 2)

CREATE PROCEDURE PSS_ACCOUNT_BY_EMAIL
    @ACC_EMAIL VARCHAR(150)
AS
BEGIN
    SELECT
        ACC_ID,
        ACC_EMAIL,
        ACC_PASSWORD,
        ACC_ROL_ID
    FROM ACCOUNT
    WHERE ACC_EMAIL = @ACC_EMAIL
    ORDER BY ACC_ID ASC
END

CREATE PROCEDURE PSI_ACCOUNT
    @ACC_EMAIL VARCHAR(150),
    @ACC_PASSWORD VARCHAR(255),
    @ACC_ROL_ID INT
AS
BEGIN
    INSERT INTO ACCOUNT (ACC_EMAIL, ACC_PASSWORD, ACC_ROL_ID)
    VALUES (@ACC_EMAIL, @ACC_PASSWORD, @ACC_ROL_ID);
END

CREATE PROCEDURE PSS_ACCOUNT
AS
BEGIN
    SELECT
        ACC_ID,
        ACC_EMAIL,
        ACC_PASSWORD,
        ACC_ROL_ID
    FROM ACCOUNT
    ORDER BY ACC_EMAIL ASC
END

CREATE PROCEDURE PSU_ACCOUNT
    @ACC_ID INT,
    @ACC_EMAIL VARCHAR(150),
    @ACC_PASSWORD VARCHAR(255),
    @ACC_ROL_ID INT
AS
BEGIN
    UPDATE ACCOUNT
    SET
        ACC_EMAIL = @ACC_EMAIL,
        ACC_PASSWORD = @ACC_PASSWORD,
        ACC_ROL_ID = @ACC_ROL_ID
    WHERE ACC_ID = @ACC_ID
END

CREATE PROCEDURE PSD_ACCOUNT
    @ACC_ID INT
AS
BEGIN
    DELETE FROM ACCOUNT
    WHERE ACC_ID = @ACC_ID
END