services:
  mysql:
    image: mysql:8.0
    container_name: erasmove-db
    environment:
      MYSQL_ROOT_PASSWORD: SuperMotDePasse!123
      MYSQL_DATABASE: ErasmoveDb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: erasmove-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  mysql_data: