INSERT INTO ROLE (ROL_LIBELLE) VALUES ('Gestionnaire');
INSERT INTO ROLE (ROL_LIBELLE) VALUES ('Voyageur');

INSERT INTO UTILISATEUR (UTI_NOM, UTI_PRENOM, UTI_LOGIN, UTI_MOTDEPASSE, ROL_ID)
VALUES ('Admin', 'System', 'bocba@cba.fr', LOWER(CONVERT(NVARCHAR(64), HASHBYTES('SHA2_256', 'mdp'), 2)), 1);
INSERT INTO UTILISATEUR (UTI_NOM, UTI_PRENOM, UTI_LOGIN, UTI_MOTDEPASSE, ROL_ID)
VALUES ('User', 'System', 'focba@cba.fr', LOWER(CONVERT(NVARCHAR(64), HASHBYTES('SHA2_256', 'mdp'), 2)), 2);

INSERT INTO TYPE_TRANSPORT (TYP_LIBELLE) VALUES ('Avion');
INSERT INTO TYPE_TRANSPORT (TYP_LIBELLE) VALUES ('Train');
INSERT INTO TYPE_TRANSPORT (TYP_LIBELLE) VALUES ('Bus');