CREATE TABLE ROLE (
    ROL_ID INT IDENTITY(1,1) NOT NULL,
    ROL_LIBELLE VARCHAR(50) NOT NULL,
    CONSTRAINT PK_ROLE PRIMARY KEY (ROL_ID)
);

CREATE TABLE TYPE_TRANSPORT (
    TYP_ID INT IDENTITY(1,1) NOT NULL,
    TYP_LIBELLE VARCHAR(50) NOT NULL,
    CONSTRAINT PK_TYPE_TRANSPORT PRIMARY KEY (TYP_ID)
);

CREATE TABLE UTILISATEUR (
    UTI_ID INT IDENTITY(1,1) NOT NULL,
    UTI_NOM VARCHAR(50) NOT NULL,
    UTI_PRENOM VARCHAR(50) NOT NULL,
    UTI_LOGIN VARCHAR(50) NOT NULL,
    UTI_MOTDEPASSE VARCHAR(255) NOT NULL,
    ROL_ID INT NOT NULL,
    CONSTRAINT PK_UTILISATEUR PRIMARY KEY (UTI_ID),
    CONSTRAINT FK_UTILISATEUR_ROLE FOREIGN KEY (ROL_ID) REFERENCES ROLE (ROL_ID)
);

CREATE TABLE LIEU (
    LIE_ID INT IDENTITY(1,1) NOT NULL,
    LIE_NOM VARCHAR(100) NOT NULL,
    LIE_VILLE VARCHAR(100) NOT NULL,
    LIE_PAYS VARCHAR(100) NOT NULL,
    LIE_LATITUDE FLOAT NOT NULL,
    LIE_LONGITUDE FLOAT NOT NULL,
    CONSTRAINT PK_LIEU PRIMARY KEY (LIE_ID)
);

CREATE TABLE TRANSPORT (
    TRA_ID INT IDENTITY(1,1) NOT NULL,
    TRA_COMPAGNIE VARCHAR(100) NOT NULL,
    TYP_ID INT NOT NULL,
    CONSTRAINT PK_TRANSPORT PRIMARY KEY (TRA_ID),
    CONSTRAINT FK_TRANSPORT_TYPE_TRANSPORT FOREIGN KEY (TYP_ID) REFERENCES TYPE_TRANSPORT (TYP_ID)
);

CREATE TABLE TRAJET (
    TRJ_ID INT IDENTITY(1,1) NOT NULL,
    LIE_ID_DEPART INT NOT NULL,
    LIE_ID_ARRIVEE INT NOT NULL,
    TRA_ID INT NOT NULL,
    CONSTRAINT PK_TRAJET PRIMARY KEY (TRJ_ID),
    CONSTRAINT FK_TRAJET_LIEU_DEPART FOREIGN KEY (LIE_ID_DEPART) REFERENCES LIEU (LIE_ID),
    CONSTRAINT FK_TRAJET_LIEU_ARRIVEE FOREIGN KEY (LIE_ID_ARRIVEE) REFERENCES LIEU (LIE_ID),
    CONSTRAINT FK_TRAJET_TRANSPORT FOREIGN KEY (TRA_ID) REFERENCES TRANSPORT (TRA_ID)
);

CREATE TABLE VOYAGE (
    VOY_ID INT IDENTITY(1,1) NOT NULL,
    VOY_LIBELLE VARCHAR(100) NOT NULL,
    UTI_ID INT NOT NULL,
    VOY_DATE_CREATION DATETIME DEFAULT GETDATE(),
    CONSTRAINT PK_VOYAGE PRIMARY KEY (VOY_ID),
    CONSTRAINT FK_VOYAGE_UTILISATEUR FOREIGN KEY (UTI_ID) REFERENCES UTILISATEUR (UTI_ID)
);

CREATE TABLE VOYAGE_ETAPE (
    VOY_ID INT NOT NULL,
    TRJ_ID INT NOT NULL,
    VET_ORDRE INT NOT NULL,
    CONSTRAINT PK_VOYAGE_ETAPE PRIMARY KEY (VOY_ID, TRJ_ID),
    CONSTRAINT FK_VET_VOYAGE FOREIGN KEY (VOY_ID) REFERENCES VOYAGE (VOY_ID),
    CONSTRAINT FK_VET_TRAJET FOREIGN KEY (TRJ_ID) REFERENCES TRAJET (TRJ_ID)
);